### ISSUE TITLE
Respond with 301 instead of 404 for content with redirect

### ISSUE THREAD

**Issue by johannesmols** [umbraco/Umbraco.Heartcore.Issues#100]
### Issue description

Hello,

I'm working on a new Heartcore solution and we are now looking into getting redirects to work.
Besides it not being possible to create manual redirects, it seems that the [Content Delivery API](https://docs.umbraco.com/umbraco-heartcore/api-documentation/content-delivery/content) does not take redirects into account. At the moment, it is only possible to redirect by manually retrieving ALL redirects from the [Redirect API ](https://docs.umbraco.com/umbraco-heartcore/api-documentation/redirect/) and finding the correct one for the current page.

I would find it much more intuitive if the Content Delivery API returned a 301 with the Location header instead of a 404. At the very least, it should be possible to query the Redirect API for a URL directly so that one doesn't have to load all redirects. For large solutions, those redirects will accumulate quickly and at some point it will slow an application down if it first has to download thousands of redirects and then manually figure out for every page load whether there is one, whether there have been updates to it, etc.

A simple example:
![image](https://github.com/umbraco/Umbraco.Heartcore.Issues/assets/11809436/135711a3-e4eb-4cae-9575-d4cc9345145e)

Querying the old URL:
![image](https://github.com/umbraco/Umbraco.Heartcore.Issues/assets/11809436/d3102045-6dbf-4985-90e2-b8788adab327)

Expected behaviour:
A 301 response with the Location header set to "/insights/logistics/"

**Comment by jmf-umbraco** [comment]
Hi @johannesmols, thanks for your suggestion.

Unfortunately at this time we are not going to implement this change. It would be a breaking change, and additionally we are concerned about some of the technical implementations of caching & 301 responses.
