### ISSUE TITLE
Cloudflare edge nodes serve different content versions after publish

### ISSUE THREAD

**Issue by tomconversion** [umbraco/Umbraco.Heartcore.Issues#101]
### Issue description

Hi All,

On Friday (AU time) we started seeing some strange behaviour with the GraphQL caching.

Essentially the Cloudflare cache that sits in front of GraphQL stopped clearing consistently. We have been working on this project for weeks without issue and during content noticed stale content showing up.

We can replicate this in Postman by saving and publishing a change. Fields in the Graphql response that should be updated are not. The response headers still have CF-Cache-Status = HIT. We would expect that after saving and publishing the node Cloudflare's cache would get cleared appropriately. "cf-cache-status = dynamic" should be the header received after saving and publishing I would imagine.

What is even stranger is that if we keep submitting the same query we get CF-Cache-Status = HIT, which you would expect. However, we can see it's hitting multiple different Cloudflare edge machines (CF-Ray = 7dca68266f63a97f-SYD, 7dca72fc4b78aacb-SYD) and we have witnessed content versions from up to 3 versions ago getting returned. This all points to the Cloudflare cache not being cleared properly.

Is anyone else experiencing issues at the moment?

We have made two screen recording videos showing the issue in the API from Postman requests.   The 2nd video below shows the actual cache headers and how different Cloudflare edge nodes return older versions. 

- [https://www.youtube.com/watch?v=kiCcLrJtQSc](https://www.youtube.com/watch?v=kiCcLrJtQSc)
- [https://www.youtube.com/watch?v=4ZSfKyLwjn0](https://www.youtube.com/watch?v=4ZSfKyLwjn0)  set video quality to 720p and go full screen to see detail.
 
Thanks for any assistance. much appreciated.

**Comment by dannyatconversion** [comment]
we have raised the issue on umbraco chat as well, but haven't received any response yet
![image](https://github.com/umbraco/Umbraco.Heartcore.Issues/assets/124010045/77d03fd1-ce1a-4afd-9ac3-2a70472a7dde)
![image](https://github.com/umbraco/Umbraco.Heartcore.Issues/assets/124010045/987174ac-77f6-49eb-9ced-6cf0ea49a665)

**Comment by dannyatconversion** [comment]
we have tried this on another Umbraco test project and the same issue can be observed here as well.  This looks like a bug in Umbraco's CDN based caching mechanism

**Comment by jmf-umbraco** [comment]
Thanks for bringing this to our attention.

Unfortunately this is a current limitation of content delivery in Heartcore. We are using [Cloudflare Workers KV](https://developers.cloudflare.com/workers/learning/how-kv-works#consistency), which have a TTL of up to "60 seconds or more" for each individual edge node once we invalidate the cache.

Given that the resulting behaviours are particularly undesirable for content authors:

- Who must wait up to a minute or more for updated content to become visible
- Who may see potentially outdated content from KV node that hasn't yet had its cache invalidated, even after seeing newer content on a prior request

Then we have raised a backlog issue to take a deeper look at our caching approach and determine whether we can solve for these.

We do not presently have a timeframe, but will update this issue thread when we know more.

**Comment by jmf-umbraco** [comment]
Hi Tom,

The long delays you experienced are likely due to a Cloudflare issue that caused delays in writing to the KV store. Cloudflare have marked the incident [resolved](https://www.cloudflarestatus.com/incidents/z5ydtlhxcxf5), so are you please able to re-check and let us know if you are still experiencing the issue?

**Comment by tomconversion** [comment]
Thanks for the update Jordan. 

Yesterday we did notice things improved dramatically. We will continue to monitor from our end. 

Appreciate this issue was at Cloudflare's end and it seems even they picked it up well after the fact. It could be an idea to add some automated health checks around cache clearing to the Heartcore cloud status pages.   https://status.umbraco.io/  As that is the first place we looked for guidance when the issue started happening.

**Comment by jmf-umbraco** [comment]
We'll take that suggestion into consideration.

In the meantime, I will leave this issue open for discussion and to track the staggered cache invalidation issue.

**Comment by jmf-umbraco** [comment]
Hi @tomconversion,

In the time since the Cloudflare partial outage that caused this behaviour, we have not witnessed it happening again, and we are therefore going to close off this card as something we don't believe is a problem in Heartcore.

If you are still experiencing unusual behaviour, please feel free to re-open or raise a support ticket 🙂
