### ISSUE TITLE
Blocklist with alias of Navigation rendering incorrectly in CMS

### ISSUE THREAD

**Issue by adam1403csi** [umbraco/Umbraco.Heartcore.Issues#103]
### Issue description

Hi, 

We have a Black-list setup with an alias of navigation, the "Add Item" button is then rendering over the top of the Blocklist Items
 
![image](https://github.com/umbraco/Umbraco.Heartcore.Issues/assets/91254461/f38b78b3-a1e2-4fe9-83ed-bad858827cf0)

This looks to be because there is styling targeting the "navigation" ID which is then absolutely positioning the element 
![image](https://github.com/umbraco/Umbraco.Heartcore.Issues/assets/91254461/6536e2ca-5aab-4ec8-90f5-c3f15eb5a010) causing it to overlay the blocklist items themself. Removing the position absolute via the debug console correctly positions the button.

**Comment by adam1403csi** [comment]
Is there any chance of a resolution for this / indication of it it will be picked up as I don't want to have to change the structure of a site to work around the above issue.

**Comment by jmf-umbraco** [comment]
Hi Adam,

Thanks for raising this with us. Unfortunately the behaviour you are seeing is a limitation of the underlying CMS and we do not plan to resolve it.

However, you can work around this by giving your property an alias other than `navigation`. It is the property alias that is converted to a CSS class - so you can still set the display name of the property to `Navigation` for your content authors. I hope this helps.
