### ISSUE TITLE
Feature Request : Limit number of document type

### ISSUE THREAD

**Issue by fdwizz** [umbraco/Umbraco.Heartcore.Issues#104]
### Issue description

Hi, 

I would love to be able to limit the number of child nodes for a give type. 

i.e. : I'm creating a landing pages builder. I've setup a "Landing Pages Foder" list in my Content tree. Inside this folder I can create as much "Landing Page" document type as I want to. But I'dd like to be able to limit 1 "Homepage" Document Type for each "Landing Page" document, so that I can ensure the user wont create multiple homepage, and also I can request for this type and ensure I'll get only 1 by Landing Page. 

Feel free to contact me for more details on my issue. I'll be more than glad to be able to help to sort this out. 

Regards,

**Comment by fdwizz** [comment]
**CURRENT WORKAROUND**

What I do currently to workaround this issue is I create a "child page picker" which is setup to allow only the "Homepage" type, starting node is set to "$site" and limit to 1 entity. 

But this is a very cumbersome way to handle the tree node that show visually.

**Comment by jmf-umbraco** [comment]
Hi @fdwizz,

Thanks for your suggestion!

Heartcore is built upon Umbraco CMS and this feature would need to be created in the underlying CMS. It looks like it has been [raised before](https://github.com/umbraco/Umbraco-CMS/issues/10288), so I suggest you add your thoughts to the discussion there.
