### ISSUE TITLE
Updating a Block list under data type does not affect document types suing it.

### ISSUE THREAD

**Issue by nathLanzetti** [umbraco/Umbraco.Heartcore.Issues#107]
### Issue description

I have this issue where when I create a new block and add it to my block list the content won't show in graphql Query.
I'm updating the block list here : 
![image](https://github.com/umbraco/Umbraco.Heartcore.Issues/assets/91882514/c171fc00-c643-47f6-827a-bbbf146ebe89)

In the content panel, I can add and see the new block I just created.
For my new block to be visible in graphql, I need to save every document types that uses it in the settings panel.

Here's how this can be reproduced : 
1. Create an Element Type
2. Edit blocklist data type (see screenshot for where to edit it)
3. Go to content and add the new block to the blocklist
4. Save and Publish node
5. New block is not present in my graphql query

**Comment by jmf-umbraco** [comment]
Hi @nathLanzetti, thanks for your issue report.

Unfortunately we are unable reproduce this at our end. We suspect it might be an issue with only your project. If you are still experiencing the problem, your best avenue for getting this one solved is to create a support ticket.
