### ISSUE TITLE
Feature request : Switch on the font and background color options in RTE

### ISSUE THREAD

**Issue by dydimitrov** [umbraco/Umbraco.Heartcore.Issues#110]
### Issue description

When working with RTE field is nice to have the ability to highlight some phrases, sentences or words in order to achieve some focus on specific parts of the text.

Currently, we have to use the format options by including some specific inline style options but it is hard to cover all of the options that the editor could possibly want.

Please could you add the colouring options in RTE.

**Comment by jmf-umbraco** [comment]
Hi @dydimitrov. Thanks for the suggestion!

We'll take a look into it and see which additional TinyMCE features we can make available in Heartcore, if any. This isn't a high priority for us, but we might be able to slip something in with some other config changes we're making.

**Comment by jmf-umbraco** [comment]
Hi @dydimitrov,

We are pleased to inform you that this was indeed a change we were able to make. Unfortunately we have been forced to batch it with an ongoing dependency upgrade of the core CMS.

We will be rolling out this dependency upgrade for new Heartcore sites in either December or January, whereas existing sites will get it slightly later - most likely before end of Q1 2024.

**Comment by jmf-umbraco** [comment]
We've just rolled out a version of Heartcore that fixes this issue for all sites created after 12th February 2024. Existing sites will have this rolled out in Q2 this year.

**Comment by dydimitrov** [comment]
Great to hear that. Thank you
