### ISSUE TITLE
Feature Request: Prompt before deleting linked content items and assets

### ISSUE THREAD

**Issue by amelia-luminary** [umbraco/Umbraco.Heartcore.Issues#111]
### Issue description

We have come across issues where content editors are able to delete content items and media assets which are used/linked in other content items. This causes build failures when building static websites. 

In it's current state its very easy for a content editor to delete a content item/media asset and unknowingly break the build because there's no prompt letting them know that what they're about to delete is linked to something else that requires it. 

When deleting a content item/media asset the content editor should be prompted if that particular item is linked/used in another content item. Then the content editor should be given the option to explicitly proceed knowing the risk of deleting this item, or cancelling the deletion. Alternatively, being given the option to delete any dependent items in the same action.

I believe having a prompt like this will not only prevent the content editor from breaking the build, but also helps them maintain their content more efficiently. Not to mention, it will also alleviate devs having to add a lot of layers/null checks for required/mandatory fields to prevent such breaks from occurring.

**Comment by jmf-umbraco** [comment]
We've just rolled out a version of Heartcore that fixes this issue for all sites created after 12th February 2024. Existing sites will have this rolled out in Q2 this year.
