### ISSUE TITLE
Adding a new Element Type to a current Block List is not returned in get request

### ISSUE THREAD

**Issue by kevlarAdmin** [umbraco/Umbraco.Heartcore.Issues#115]
### Issue description

If you have a page which is using a Block List already and you are adding another valid Element Type to that Block List and then add the new Element Type to the page. It wont return that new Element Type.

> Would like to get the new element type if it has been added after.

![Skärmbild 2023-09-29 095730](https://github.com/umbraco/Umbraco.Heartcore.Issues/assets/59009197/676e939a-3c88-4d66-8886-0f07939ed034)
![Skärmbild 2023-09-29 095748](https://github.com/umbraco/Umbraco.Heartcore.Issues/assets/59009197/ebc59c24-871d-4565-a032-3d293c19134e)

**Comment by jmf-umbraco** [comment]
Hi @kevlarAdmin, thanks for your issue report!

Unfortunately this sounds like a problem that is specific to your site. We would expect all elements to be returned in your described scenario. If you continue to be troubled by this one, please raise a support ticket from the Cloud portal.
