### ISSUE TITLE
GraphQL - Get total item count when using pagination

### ISSUE THREAD

**Issue by vsilvar** [umbraco/Umbraco.Heartcore.Issues#124]
### Summary

Currently it doesn't seem to be possible to retrieve the total number of items (or pages) when using a paginated query.
Example:
```graphQL
  allContent(first: 10){
    pageInfo {
      hasNextPage
      endCursor
    }
    items {
      name
    }
  }
```

For several different UX scenarios it's sometimes useful to have the total count.

This does seems to be supported by `pg_graphql` as an opt-in field (which I think Heartcore uses?)
https://supabase.github.io/pg_graphql/configuration/#totalcount

**Comment by rasmusjp** [comment]
Hi @vsilvar

Thanks for the feature request. I don't recall the reason for not including the total count, so we'll need to investigate if it's possible with the way we do pagination and filtering.

Just for reference, we don't use `pg_graphql` but [GraphQL.NET](https://graphql-dotnet.github.io/docs/getting-started/introduction/) with our own library [JoinMonster.NET](https://github.com/umbraco/join-monster-dotnet/tree/master)

**Comment by vsilvar** [comment]
Hi @rasmusjp,
not sure why I thought `pg_graphql` was used, but good to know what's actually being used under the hood 🙂

**Comment by jmf-umbraco** [comment]
Hi @vsilvar,

We're happy to inform you that not only is this something that we found possible, but have now implemented. We will roll it out in the next day or two and let you know when it is available on live. 🙂

**Comment by jmf-umbraco** [comment]
This has now been rolled out to live. 🙂
