### ISSUE TITLE
GraphQL - Pagination with endCursor not working correctly

### ISSUE THREAD

**Issue by StijnAvdL** [umbraco/Umbraco.Heartcore.Issues#126]
### Summary

I have wrote a graphQL query with `pageInfo` so i can make a pagination over my news articles. But if I use the given `endCursor` as parameter for the `after` option in `allArticleItem` it doesn't not return and new items even if the pageInfo.hasNextPage said there are more items in the collection. My query looks like this:

```
{
  allArticleItem(first: 6, orderBy: publicationDate_DESC, after: "endCursor_string"){
    items {    ...    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
}
```

### Steps to reproduce

- Make 13 of articles items
- Use the query above with first 6
- Then use the endCursor given in the `after` option
- Now it will return no items

### Expected result

- I expect to receive items back from the query for the 2de item.  

### Actual result

I dont receive any items after running the query with after option

**Comment by StijnAvdL** [comment]
I found the issue myself. 

Because it sorts on publicationDate that field needs to be required and not empty. If I decode the endCursor the first result gave a correct set publicationDate that is the `j` value in the code below:

```
{
  "j": "2023-05-17T00:00:00Z",
  "k": [
    0,
    0,
    2,
    0,
    2
  ],
  "l": "2023-05-23T12:00:34.427",
  "b": "2f8701ab-8483-4772-9b85-54930ecf600c"
}
```
but the next one gave gave back  `0001-01-01T00:00:00` as publicationDate:

```
{
  "j": "0001-01-01T00:00:00",
  "k": [
    0,
    0,
    2,
    0,
    7
  ],
  "l": "2023-06-30T08:02:50.22",
  "b": "d18c7745-8294-4839-a720-0b3792196e73"
}
```
After setting al publicationDate the issue was fixed and GraphQL queries worked as they should. Some better error message would be nice :)

**Comment by jmf-umbraco** [comment]
Hi @StijnAvdL,

Great to hear that you managed to find a solution, however I do think the behaviour you describe is defective. We _should_ still allow ordering by fields that may be null.

We will attempt to reproduce and will be in touch letting you know whether this is something we will pick up and fix.

**Comment by jmf-umbraco** [comment]
We have released a fix for this today. It should no longer be mandatory to provide a value for datetime fields in order for pagination to work in GraphQL.
