### ISSUE TITLE
Umbraco Heartcore - Webhooks- Multiple Content Types added for webhook (P3)

### ISSUE THREAD

**Issue by zacheatonvp** [umbraco/Umbraco.Heartcore.Issues#13]
### Issue description

Would we be able to attach multiple content types onto webhook configuration rather than just single type?

This would help drastically with bypassing wildcard approaches, as sometimes some events fire which are not intended. 

![image](https://user-images.githubusercontent.com/82599541/130934491-dfe6d740-4bed-4ed1-b6f2-6c70f8a88771.png)

**Comment by sitereactor** [comment]
Updated with note from the team as 'Under consideration'.
Once this has been prioritized for an upcoming sprint, we will update the feature request.

**Comment by jmf-umbraco** [comment]
I realise it's been some time since this issue was last updated, but we're still keeping an eye on it and intend to support it as soon as we can.

**Comment by jmf-umbraco** [comment]
We have now aligned the UI for Heartcore's webhooks with the same feature from the core CMS, which means you can now select multiple content types & events in the same hook.

Hooks in Heartcore are still fired from the delivery platform, meaning you get all the usual delivery guarantees etc. as before.
