### ISSUE TITLE
Forms in (cloud) heartcore: Page (button) conditions not present in form definition from Umbraco Forms API for heartcore

### ISSUE THREAD

**Issue by wvankesteren-ax** [umbraco/Umbraco.Heartcore.Issues#130]
### Summary

Would like to use the page conditions in a form definition in Umbraco Heartcore to conditionally show the submit button on the frontend.

### Steps to reproduce

create page conditions on a form and get the form definition through the Umbraco Forms Api for heartcore

### Expected result

(button) conditions entry in the page definition in the form definition as received from the Umbraco Forms Api.
Just like for groups and fields.

note: I also noticed that there could be conditionals for columns, but there is no UI for it in the backend and also not present in the form definition as received from the Umbraco Forms Api)

### Actual result

no page/button conditionds

**Comment by jmf-umbraco** [comment]
Hi @wvankesteren-ax,

Thanks for the report! We've created a fix for this and will be rolling it out to a subset of sites soon.

Unfortunately, sites that existed prior to February 12th this year will not get the fix until some time in Q2.

**Comment by martijnbeumers** [comment]
@jmf-umbraco alright, thanks for the update. Lets hope that our project is first in line for migration.

**Comment by martijnbeumers** [comment]
@jmf-umbraco  any updates on this issue?

**Comment by jmf-umbraco** [comment]
Hi @martijnbeumers! The update to existing sites is a somewhat large one, so we're still undergoing testing & stabilisation at the moment. Current best-guess for starting to roll it out to live sites is mid-June. We'll be updating our status page & sending an email to the technical contact of each site with more details about what to expect soon.

**Comment by jmf-umbraco** [comment]
Hi @martijnbeumers,

This has now been released to all existing sites, so it should be fixed!

**Comment by ustadstar** [comment]
Hi @jmf-umbraco,

This still seems to be an issue, I have created a test form in our heartcore project:

![image](https://github.com/user-attachments/assets/59a47b21-6c9a-4d38-b606-64c6ab67c9af)

When I retrieve the form trough the management API, I get the following response back:

`{
  "_id": "e9bc66f0-b0c3-48ee-8d8a-2555409d3711",
  "indicator": "*",
  "name": "Test form AS-13768",
  "nextLabel": "Next",
  "previousLabel": "Previous",
  "submitLabel": "Submit",
  "disableDefaultStylesheet": false,
  "fieldIndicationType": "NO_INDICATOR",
  "hideFieldValidation": false,
  "messageOnSubmit": "Thank you",
  "showValidationSummary": false,
  "pages": [
    {
      "caption": "PAGE ONE",
      "fieldsets": [
        {
          "columns": [
            {
              "width": 12,
              "fields": [
                {
                  "caption": "Consent for storing submitted data",
                  "alias": "dataConsent",
                  "required": true,
                  "requiredErrorMessage": "Consent is required to store and process the data in this form.",
                  "settings": {
                    "acceptCopy": "Yes, I give permission to store and process my data",
                    "showLabel": ""
                  },
                  "type": "dataConsent"
                },
                {
                  "caption": "Number",
                  "alias": "number",
                  "required": false,
                  "requiredErrorMessage": "Please provide a value for Number",
                  "settings": {
                    "defaultValue": "",
                    "placeholder": "",
                    "showLabel": "True",
                    "maximumLength": "",
                    "fieldType": "number",
                    "autocompleteAttribute": "",
                    "pattern": "^[0-9]*$",
                    "patternInvalidErrorMessage": "Please provide a valid value for Number"
                  },
                  "type": "text"
                }
              ]
            }
          ]
        }
      ]
    }
  ],
  "rel": "forms",
  "_links": {
    "self": {
      "href": "https://api.umbraco.io/forms/e9bc66f0-b0c3-48ee-8d8a-2555409d3711"
    },
    "root": {
      "href": "https://api.umbraco.io/forms",
      "title": "Forms"
    }
  }
}`

As you can see I do not receive the page condition in the response body.

**Comment by jmf-umbraco** [comment]
Hi @ustadstar,

The change we rolled out was for the Delivery API, not the Management API. In general, we recommend using the Delivery API wherever possible, as the Management API will undergo significant change once Heartcore eventually adopts Umbraco v14.
