### ISSUE TITLE
Improving File Size Constraints and Image Optimization

### ISSUE THREAD

**Issue by Hanskrogh** [umbraco/Umbraco.Heartcore.Issues#131]
### Summary

Currently, there is no mechanism to prevent users from uploading excessively large files to Umbraco Heartcore. This product faces significant challenges when handling large files, including issues with serving, optimizing, and transferring media.

It appears that you are using Cloudflare for content delivery. However, it is unclear whether the performance issues stem from Cloudflare or from Umbraco Heartcore itself. I have observed that when media files are uploaded and served through Azure CDN or AWS CloudFront, the content delivery performance is markedly faster.
<img width="1669" alt="Screenshot 2024-05-21 at 11 30 22" src="https://github.com/umbraco/Umbraco.Heartcore.Issues/assets/43749842/41bae679-f485-4c10-a099-d5ca876a6745">

Additionally, I have a comparative analysis of image optimization between Umbraco Heartcore and Contentful. For the same image, Umbraco Heartcore takes 2.7 seconds to optimize, whereas Contentful takes only 1.7 seconds. This significant difference in performance further highlights the optimization challenges faced by Umbraco Heartcore.

### Use case

I have encountered significant challenges when uploading and managing large media files. These challenges primarily stem from the platform's current inability to efficiently handle large files, resulting in delays and performance issues.

Specifically, the issues include:

- Media Optimization Delays: For example, an image optimization comparison shows that Umbraco Heartcore takes 2.7 seconds to optimize a single image, whereas Contentful completes the same task in just 1.7 seconds.

- Content Delivery Inefficiencies: Serving media files through Cloudflare, as currently configured in Umbraco Heartcore, is notably slower compared to other CDNs such as Azure CDN and AWS CloudFront, which deliver content much faster.

These inefficiencies hinder user experience and system performance. To address these issues, it would be beneficial to implement mechanisms that prevent the upload of excessively large files, enhance the platform's media optimization capabilities, and reconsider the CDN configuration to ensure faster and more reliable content delivery. This change is crucial for improving overall system performance and user satisfaction.
```[tasklist]
### Tasks
```

**Comment by jmf-umbraco** [comment]
Hi @Hanskrogh,

Thanks for the report!

We are aware that image processing times could be faster and we've identified a fix that should noticeably speed up these requests.

While it's possible to _upload_ large images in Heartcore, it is not possible to process (i.e. crop/resize) images that are excessively large. This is not what is slowing image processing - our fix targets something else.

I'll update here once the fix is released.

**Comment by Hanskrogh** [comment]
@jmf-umbraco Looking forward to the improvement! :)

**Comment by jmf-umbraco** [comment]
Hi @Hanskrogh,

We released a change last week to the image service that should have taken a load off it, allowing it to respond to image processing requests a lot faster.

Let us know if you continue to have any issues.

**Comment by Hanskrogh** [comment]
Hi @jmf-umbraco 

seems like it is not working....

<img width="863" alt="Screenshot 2024-06-03 at 11 08 07" src="https://github.com/umbraco/Umbraco.Heartcore.Issues/assets/43749842/31302384-ed24-43b8-b5d0-1c109e91d966">
