### ISSUE TITLE
TinyMCE stripping style attribute from table element

### ISSUE THREAD

**Issue by marcusferbrache** [umbraco/Umbraco.Heartcore.Issues#134]
### Summary

I am trying to style the table element to specify the width of the table but when I preview or publish the page the style attribute has been stripped out.

### Steps to reproduce

Create a page. Add a table. In the HTML view, add style="width:10em;" on the table element. Publish. View source on published page.

### Expected result

Style attribute should be visible in published page

### Actual result

Style attribute missing

**Comment by jmf-umbraco** [comment]
Hi @marcusferbrache,

Thanks for the report. This should be allowed, we'll take a look into what's going wrong and will keep you posted.

**Comment by jmf-umbraco** [comment]
Hi @marcusferbrache,

We've spent some time trying to reproduce this issue on a fresh site and have thus far been unable to. If this continues to affect you, we recommend you raise a support ticket through the Cloud portal so that we can direct investigative efforts toward your specific site.
