### ISSUE TITLE
Prevalue sources are not returned in GraphQL on the new Heartcore platform/version

### ISSUE THREAD

**Issue by sergiutesu** [umbraco/Umbraco.Heartcore.Issues#135]
### Summary

When using GraphQL to query Umbraco Forms prevalue sources it returns empty while using the manually filled values works fine.

### Steps to reproduce

1. Create a form Multiple choice picker 
2. Create some Prevalue source and hook it into a content root node to get the values from.
![image](https://github.com/user-attachments/assets/5390492a-2171-4ff6-baef-71bca492a556)

4. Configure the Form Multi choice picker to use the Prevalue sources
![image](https://github.com/user-attachments/assets/7badb643-4db0-410e-a701-0ca4393931ce)

5. Add another field with another Multi choice picker but manually fill the values 
![image](https://github.com/user-attachments/assets/dc894409-8254-482d-b497-f0fbfd6adfff)

5. Query everything example:

```
query {
allHomepage(first: 1) {
items {
__typename
id
picker {
... on FormPage {
id
formSelected
}
}
testC
}
}
}
```

6. Check the result to see the prevalue sources are not working but the manually filled ones are 

### Expected result

Getting the prevalue soruces in GraphQL

### Actual result

The prevalues are emtpy
![image](https://github.com/user-attachments/assets/29556538-3275-4af8-9559-40c6194cd8a1)

**Comment by jmf-umbraco** [comment]
Thanks for the detailed report @sergiutesu.

While this issue slipped under our radar slightly, getting a fix in place did not. We resolved this in a release some several weeks ago!
