### ISSUE TITLE
Workflow features for Umbraco Heartcore

### ISSUE THREAD

**Issue by PercyMorgan** [umbraco/Umbraco.Heartcore.Issues#137]
### Summary

Workflow with a wide range of features that allow you to design custom content approval processes to fit the organization.  This will allow content managers and copywriters to review, approve, and publish with confidence. Also to have audit trails and reporting on the activities.

### Use case

his will allow content managers and copywriters to review, approve, and publish with confidence. Also to have audit trails and reporting on the activities.

**Comment by jmf-umbraco** [comment]
Hi @PercyMorgan,

Thanks for your suggestion! Fortunately, this is a feature we already intend to deliver. You can find further information on our [public roadmap](https://umbraco.com/products/knowledge-center/roadmap/). When we start to work on this, it will move from the 'Next' section to 'Now'.

As this is tracked by the roadmap already, I'm going to close this issue off.
