### ISSUE TITLE
Redirect API query

### ISSUE THREAD

**Issue by daveve80** [umbraco/Umbraco.Heartcore.Issues#140]
### Summary

At this moment the redirect API ( https://cdn.umbraco.io/redirect ) is limited to 1000 redirects, whenever we'd hit that limit, the old (or new) pages won't get redirected anymore, because we simply can't fetch more. Much faster and friendlier would be to query the redirect API directly so we don't have to fetch all 1000 results on each and every page that has a redirect.

E.g.

I am now using:
`const redirects = await client.delivery.redirect.getAll()`

Which returns an object with ALL redirects.

Something along the line of:
```
const searchstring = "/fullpath/page/this-is-the-detail-page"/
const redirects = await client.delivery.redirect.getAll(searchstring)
```

Which I expected to return the specific page.

### Use case

Sometimes and URL will change, because the content changes. In such a case, we would like the visitor to be redirected to the new url, because otherwise he'll end up with a 404 error. This is now possible, but limited for 1000 redirects only. Might be less, if each and every node is counted. For example if I change the node with lots of childeren under it, one redirect might be enough to affect 1000 pages.
Next to that, fetching 1000 redirects on each and every visit might take a long time. I would like to search instantly instead so only one result is returned.

**Comment by jmf-umbraco** [comment]
Hi @daveve80,

Thanks for the suggestion!

Firstly, we could probably afford to make this a bit more obvious in our docs, but the redirect endpoint does support pagination via the `page` and `pageSize` query string parameters. For more information, see https://docs.umbraco.com/umbraco-heartcore/api-documentation/redirect

However, we still see value in your suggestion. We'll look into adding an endpoint to retrieve redirect info from a given path. No ETA at this stage, but we'll keep you posted here when we have anything to share.

**Comment by jmf-umbraco** [comment]
Hi @daveve80,

Good news - we've created this endpoint and you can expect to see that rolled out later this week. We'll also get the documentation updated to provide you with an example for how to call it.

**Comment by daveve80** [comment]
That's great news, thanks. I see the documentation has been updated already. I am going to test this as soon as a I can!

**Comment by jmf-umbraco** [comment]
Hi @daveve80, this was rolled out late last week. It should be available now 😄
