### ISSUE TITLE
content delivery api issue

### ISSUE THREAD

**Issue by digitallmn** [umbraco/Umbraco.Heartcore.Issues#17]
### Issue description

After doing a deploy on Umbraco Heartcore, nodes sometimes ‘lose’ their url and can no longer be retrieved using the Content Delivery API, causing our platform to break down.
 
We unfortunately do not have a screenshot of the situation, since we always want to fix it as soon as possible, but when this Situation occurs the yellow marked url is gone
 
 
and we instead see an error in italics: This document is published but its url cannot be routed
![issue heartcore](https://user-images.githubusercontent.com/91530174/135057260-62f06b07-d5cb-4344-9975-31793bf33617.png)
 
Before the deploy everything is fine and all the nodes have url’s. It’s really the deploy that sets things off.
 
To fix it, we go into Content -> Redirect URL Management to disable and then quickly re-enable the URL tracker. This resolves the issue.
 
Needless to say, this is a rather wonky solution and cannot avoid that we experience downtime if this occurs on a deploy. We are therefore hoping a fix can be provided.

**Comment by sitereactor** [comment]
Issues like these related t the nucache in Umbraco should have been solved.
Additionally, we have started moving all existing Heartcore projects to our Content Delivery Platform, which further aims to avoid cache related issues.

Closing as fixed.
