### ISSUE TITLE
Heartcore Bug - Environment Error Log handling (P2)

### ISSUE THREAD

**Issue by zacheatonvp** [umbraco/Umbraco.Heartcore.Issues#20]
### Issue description

Hello team, 

I have spotted some strange inconsistency with request data that you post during a PostSave event at publish time in the backoffice. 

I have made an assumption that this has directly affected my error event queue for my environments, that ultimately span 10,000+ error messages for this. 
**Replication Steps**
- Open Google Dev Tools -> Network Tab
- Publish Page
- Look at network tab for PostSave, look at request data, and you can see eventually there "key" starts to return empty guids that I believe directly flood my error log. 

**PostSave Request**
Take note of the keyIds for nested elements, they are consistently fresh GUIDs which I am happy with. 
![image](https://user-images.githubusercontent.com/82599541/139110493-57adb13d-9357-45fb-b569-56c5b94acc98.png)

Then, further down in the payload, they begin to turn into empty GUIDs. 
![image](https://user-images.githubusercontent.com/82599541/139110628-17f2abf8-e2fa-44e8-8137-31f0a498aa13.png)

**Cloud Portal - Error Logs**
We in turn get alot of these errors in the thousands. 
![image](https://user-images.githubusercontent.com/82599541/139110750-2d59ae11-3b46-475b-b802-0757dd5cbfde.png)
I believe its because the request payload in Umbraco is a bad request. 

This is currently flooding or error log, and myself and Darek believe it could be spamming and influencing some issues behind the scenes. 

Can this be looked into please?

As always, give me a shout if you want a run through.

**Comment by sitereactor** [comment]
We believe this nested content issue has been fixed already, so marking as closed.
The related CMS bug has been fixed and is incorporated into what Heartcore is currently based upon.
