### ISSUE TITLE
Graphql query children through parents selected in multi-node tree picker

### ISSUE THREAD

**Issue by Hanskrogh** [umbraco/Umbraco.Heartcore.Issues#29]
### Issue description

Is it possible to get children of the parent selected with multi-node tree picker? 

Example: 
```
{
  allPage(where: { name: "Demo Page" }) {
    items {
      components {
        __typename
        ... on FeaturedProducts {
          products {                                                           ----> Multi Node Tree picker
            ... on Product {                                                  ----> Get all the information about the node i selected (Product)
              name
              category
              featuredProduct
              sortOrder
              canBePurchased
              tags
              type
              url
              children {
                items {
                  __typename                                                 ----> Try to get Children of the selected node **** ERROR **** 
                }
              }
            }
          }
        }
      }
    }
  }
}

```

The Error backoffice playground returns is the following:
`{
  "errors": [
    {
      "message": "Error trying to resolve field 'items'.",
      "locations": [
        {
          "line": 18,
          "column": 17
        }
      ],
      "path": [
        "allPage",
        "items",
        0,
        "components",
        1,
        "products",
        0,
        "children",
        "items"
      ]
    },
    {
      "message": "Error trying to resolve field 'items'.",
      "locations": [
        {
          "line": 18,
          "column": 17
        }
      ],
      "path": [
        "allPage",
        "items",
        0,
        "components",
        1,
        "products",
        1,
        "children",
        "items"
      ]
    },
    {
      "message": "Error trying to resolve field 'items'.",
      "locations": [
        {
          "line": 18,
          "column": 17
        }
      ],
      "path": [
        "allPage",
        "items",
        0,
        "components",
        1,
        "products",
        2,
        "children",
        "items"
      ]
    }
  ],
  "data": {
    "allPage": {
      "items": [
        {
          "components": [
            {
              "__typename": "Spacer"
            },
            {
              "__typename": "FeaturedProducts",
              "products": [
                null,
                null,
                null
              ]
            },
            {
              "__typename": "Spacer"
            }
          ]
        }
      ]
    }
  }
}`

Let me know if this is working as intended or if it is a bug, that you can't selected children of a item selected through a multi-node tree picker.

**Comment by sitereactor** [comment]
Updated the type of this issue to a bug, as we need to fix the underlying lookup so it works as expected.

**Comment by sitereactor** [comment]
A fix for this issue is currently scheduled for release between 28-31. March.
Will report back when the release is scheduled and announced on statuspage.

**Comment by jmf-umbraco** [comment]
Looks like we forgot to close this issue off, but this fix was released some time ago!
