### ISSUE TITLE
Feature request: Add the preferFocalPoint crop to the URL property

### ISSUE THREAD

**Issue by RyuLindow** [umbraco/Umbraco.Heartcore.Issues#31]
### Issue description

Can we please get the preferFocalPoint crop allowed in the url property, so that you don't have to dig 2 lvls deeper to get it?

![crop](https://user-images.githubusercontent.com/56826332/146207997-02f48cd4-9fff-4d3b-800a-9c0933d32e63.png)

**Comment by jmf-umbraco** [comment]
Apologies this hasn't had attention in some time. There's some technical challenges involved, and given that there's an easy workaround we unfortunately have no plans to continue with it.
