### ISSUE TITLE
Graphql Mutation || Fix content management API 

### ISSUE THREAD

**Issue by Hanskrogh** [umbraco/Umbraco.Heartcore.Issues#34]
### Issue description

When you update a content node in a list with the Content Management API it automatically sets the updated entity sort number to length of the list +1 (n..+1), which means our content editors can't arrange items in the correct order manually, because everytime we update the content with the api, it resets the Sort Order.....

Would be nice if this could be fixed :) 

Alternatively support for Graphql mutations would be really lovely!

**Comment by Fjellvang** [comment]
Original issue has been fixed in February, and we currently don't have any plans for GraphQL mutations.
