### ISSUE TITLE
GraphQL - Umbraco Heartcore

### ISSUE THREAD

**Issue by Hanskrogh** [umbraco/Umbraco.Heartcore.Issues#41]
### Issue description

We're experiencing the following issue with our Umbraco heartcore solution:

Everytime we do an update to an document/data type, the graphql for that specific document/element will be down for a certain amount of time. When we do this on simple documents/datatypes with not a lot of references, it might take 1-5 mins, which is fine, but the issue comes when we do it to a large document/data type, then the graphql can be out of functioning for multiple hours before it is up to date.

We have a really large nested content element named  "Component picker" which is use many places on in our solution. When updating this, it takes serval minutes just to save it and once it is saved, the graphql will return an empty array, even though there is content inside it. Then we wait for some hours and it will be back functioning as it is supposed to.

Is this something you have experienced before?

**Comment by Fjellvang** [comment]
We assume this has been resolved
