### ISSUE TITLE
Url redirect management

### ISSUE THREAD

**Issue by Hanskrogh** [umbraco/Umbraco.Heartcore.Issues#45]
### Issue description

Is it possible to query url redirect management through heartcore?

I can't really see the use of it, if you're not able to query all redirected content and implement the redirects in the frontend...

We can possible solve our issue with creating a webhook and implementing a custom redirect functionality in our case, but it would be nice if we could use the build in functionality instead :)

**Comment by Fjellvang** [comment]
We've implemented support for this, you can find the documentation  [On Our.Umbraco.com](https://our.umbraco.com/documentation/Umbraco-Heartcore/API-Documentation/Redirect/)

**Comment by Hanskrogh** [comment]
@Fjellvang I am getting the following response form the api:
`{
    "error": {
        "code": "NotFound",
        "message": "No resource was found that matches the path '/cdn/redirect'."
    }
}`

**Comment by myildiz-axendo** [comment]
@Fjellvang is it possible to edit / delete redirects in heartcore?
