### ISSUE TITLE
Feature Request | Kudu console access

### ISSUE THREAD

**Issue by mgolubovic25** [umbraco/Umbraco.Heartcore.Issues#49]
### Issue description

Would it be possible to get access to the Kudu console on the Heratcore project?

We have realized that some deployment issues could probably be investigated or even solved on the developer's side without the need to contact Umbraco Support for it. 

Does this make sense to you or there are some other risks included if developers have access to this console while developing? 

Kind regards, 
Marina

**Comment by sitereactor** [comment]
Hi @mgolubovic25 thanks for the suggestion. Heartcore is a software as a service offering, so getting access to the underlying components is not possible unfortunately. Ideally things should just work 😄 
If there is tooling you are missing or something that can provide you with the necessary insights for investigating issues then please let us know, and we can look into what we can do/provide, which doesn't require access to the file system.

I'll close this feature request, but please feel free to open a new one with suggestions for what we can do to help/assist.
