### ISSUE TITLE
GraphQL support for search endpoint - Feature request

### ISSUE THREAD

**Issue by tolkienosborn** [umbraco/Umbraco.Heartcore.Issues#52]
### Issue description

Currently the only way to search all content fields is by using the REST API search endpoint:

https://our.umbraco.com/documentation/Umbraco-Heartcore/API-Documentation/Content-Delivery/content/#search

Can we add a GraphQL search endpoint? As the REST API one pulls in loads of info i may not require.

**Comment by RosenPetrov** [comment]
Hey, we also need that functionality. Even more advanced search with boosting support etc. would be nice.

**Comment by sitereactor** [comment]
Hi and thanks for submitting a feature request.

The need for a Search endpoint I understand, but not within GraphQL. Can you help me understand how you would want to use Search within GraphQL (where you already have fairly good filtering capabilities)? If you can list a few scenarios that would be super helpful.

Better search capabilities in general is something that is on the radar, but we have a couple of underlying bits that needs to be in place first.

**Comment by jmf-umbraco** [comment]
Hi all,

We have discussed this internally, and while we want to make some improvements to search in the mid-term, we don't intend to make that capability available specifically in the GraphQL API - improvements will probably take the form of a new REST-like endpoint. I am therefore closing this ticket for now.
