### ISSUE TITLE
GraphQL support for getting all URLs in all cultures for a node at once - Feature Request

### ISSUE THREAD

**Issue by RosenPetrov** [umbraco/Umbraco.Heartcore.Issues#53]
### Issue description

**Issue description**
We need to be able to get all URLs for all cultures in one API call. We need that for implementing language switcher and hreflang tags. What we need is basically the same functionality that the Content API provides when we make a request to https://cdn.umbraco.io/content/ followed with either the ID or URL for a page and the response includes this "_urls" section:
![image](https://user-images.githubusercontent.com/3617161/167783993-997ccf82-2aed-47a5-a4de-7b3ab5450427.png)

**Proposed solution**
Update the GraphQL "Content" interface type to include "urls" type containing the data provided by the "_urls" property in Content API.

Thanks
Rosen

**Comment by RyuLindow** [comment]
Hey @RosenPetrov 

Try the following

![image](https://user-images.githubusercontent.com/56826332/167799118-6bc5fd27-4fba-40c3-b383-c7d4df39aea8.png)

**Comment by RosenPetrov** [comment]
This actually works. Thank you. Will do the job for now. But it still might make sense to have all of them. Seems easier than to implicitly hardcore cultures and having to update later on if you add new language or so.

**Comment by RyuLindow** [comment]
Right, that sounds fair.

Perhaps, we could add a `where culture X` argument 🤔

**Comment by jmf-umbraco** [comment]
Apologies this hasn't received attention in some time, but unfortunately given that there is a workaround available, we have no plans to implement this at this time.
