### ISSUE TITLE
Better error message upon failed HeartCore Rest Api call

### ISSUE THREAD

**Issue by wvankesteren-ax** [umbraco/Umbraco.Heartcore.Issues#58]
### Issue description

Using Umbraco.Headless.Client.Net we are having issues when using the api (querying, updating, etc.).
In any case the api request simply returns error 500 without any additional information what's going wrong.

Please add as much as possible info about the error into the failed api request.

Looking at the umbraco's logs (through backend or Development enviroment) there could be several causes, like
 * System.OutOfMemoryException
 * System.NullReferenceException: PublishedSnapshotService
 * System.Data.SqlTypes.SqlTypeException: SqlDateTime overflow. Must be between 1/1/1753 12:00:00 AM and 12/31/9999 11:59:59 PM.
   ** more info could involve the name and value of the node and property in question
* in case a value does not reflect the datatype as defined in the document type, (e.g. storing an int into a string field)
* etc.

**Comment by wjvankesteren** [comment]
a simular issue is reported under https://github.com/umbraco/Umbraco.Heartcore.Issues/issues/2 - SQL deadlock when creating content items asynchronously.

In that issue, it is stated that "Currently this is not a feature request that is very high on our priority list unfortunately".

I think it is now time to seriously look at this kind of scenarios. There is a reason why there is a Content Management API, and it should handle this kind of loads. (it's an API, isn't it?)

**Comment by sitereactor** [comment]
With regards to the error messages that is something that we continuously improve on - for the REST API we are moving all projects to have their REST API served by our Content Delivery API, which will allow us to be in control of the error messages returned. So as projects are moved you should see an improvement there.

With regards to the Management API - its a different issue, which you could consider opening as a separate issue. Right now its a limitation in the Core CMS, which we can't immediately fix. But it is on our radar and something we will keep in mind for the next iteration of the Management API, so items can be created in batches without resulting in deadlocks.

**Comment by wjvankesteren** [comment]
Many Thanx!

At your request: https://github.com/umbraco/Umbraco.Heartcore.Issues/issues/80

**Comment by jmf-umbraco** [comment]
Now that all Heartcore projects handle API requests from our content delivery platform, we expect that the stability and error handling of requests should be a lot better than it was at the time this issue was created.

As such, I'm going to close this card. Please let us know if you experience any specific scenarios in which you get back an error response with the lack of detail you expect. Thanks!
