### ISSUE TITLE
Feature request: 2FA For Umbraco Cloud & Heartcore Backoffice

### ISSUE THREAD

**Issue by tolkienosborn** [umbraco/Umbraco.Heartcore.Issues#6]
As an existing Heartcore / Cloud user i am trying to win new business to implement in Umbraco Heartcore. But often a stumbling block is the need to secure the backoffice with 2FA to minimise the risk of stolen credentials.

**Comment by Christoph-Schmid** [comment]
> We are starting the initial work a couple of weeks from now. As we are starting off with bringing Umbraco Id to Heartcore as the first part of this work, its difficult to say for sure when the 2FA part will be added to the Cloud Portal, but a rough guestimate is end of April / beginning of May. And I expect that 2FA for the Umbraco Backoffice and the Cloud Portal will go hand in hand.

Hi, any update on this?

**Comment by sitereactor** [comment]
Hi all, yes the target date for this feature has been moved from what we originally anticipated. The work has been started, but I'm not able to give a good answer on when it will be released yet. We need to get a bit further with the implementation first.

I will update this thread as we progress, so you know what is going on.

**Comment by sitereactor** [comment]
This feature has been released and is available to all via the User Profile page. You can get to it from the Umbraco Cloud Portal or from the Backoffice - click the avatar then click "Edit your Umbraco ID profile" and from the profile page you can choose the 2 factor auth method.

Release blog post can be found here: https://umbraco.com/blog/product-update-september-16-2022/#2fa
