### ISSUE TITLE
Feature Request: Prevent autoupgrades on production (or a rollback option)

### ISSUE THREAD

**Issue by PascalIcatt** [umbraco/Umbraco.Heartcore.Issues#60]
### Issue description

At the moment Heartcore project upgrades are first deployed to development and after that automatically to production.

We would really like the option to disable this behavior and have those changes deployed manually.
At the moment these changes are actually shown on development to be deployed to live. (Bug: live already has these changes deployed)
Can we change the bug in a working feature?

Or...
If this does is not possible, can we please get rollbacks?
Or anything else to prevent production outage from upgrade failures. (maybe add custom checks to your guard system and/or guard badges?)

**Comment by sitereactor** [comment]
I understand where this is coming from given last week's incident. But it doesn't really align with Heartcore being a Software as a Service offering.
From experience, if upgrades are pushed to our users, no one will ever upgrade. So we'd prefer working to making everything extremely seamless and robust, so we avoid going done the proposed route.
Once the REST API is being served by the Content Delivery Platform for everyone, we will have a highly available API, and Backoffice upgrades will be more and more robust.

**Comment by PascalIcatt** [comment]
Thank you for the quick response and good to know what HQ's view is on this.
Is there a roadmap for serving the REST API by the Content Delivery Platform?
