### ISSUE TITLE
GraphQL: Query by ID with parent somewhere in query

### ISSUE THREAD

**Issue by jeppeschibsted** [umbraco/Umbraco.Heartcore.Issues#62]
### Issue description

Query something by id, and having `parent` somewhere in the query, nothing will be returned.

```graphql
query contentById($id: ID!) {
  allContent(where: { id: $id }) {
    items {
      id
      ... on SomethingWithParent {
        parent {
          id
        }
      }
      ... on SomethingElse {
        someField
      }
    }
  }
}
```

If `id` is `SomethingWithParent` item is returned.  
If `id` is `SomethingElse` nothing will be returned, even though it exists.  

If the `parent` field is not in the query, something will be returned, for both types.

**Comment by jeppeschibsted** [comment]
anybody?

**Comment by sitereactor** [comment]
Hi @jeppeschibsted sorry it took some time to get back to you on this one. We had a bit of vacation overlap.
We have a fix related to this issue pending. I would expect that its out by Monday, and then I'll have one of my colleagues follow up on the scenario you outlined to verify it works as expected now.

**Comment by sitereactor** [comment]
A fix for this issue has been deployed and we have checked that its working with similar queries.
