### ISSUE TITLE
Issue with child nodes being corrupted if both languages are not save and published 

### ISSUE THREAD

**Issue by thejokerd3** [umbraco/Umbraco.Heartcore.Issues#63]
### Describe the issue

When you have culture variance enabled and you create a Parent node and child nodes -> if you dont publish the parent node on both languages - It will corrupt ALL child nodes making them unaccessible. 

In the beneath screenshot you can see the node in french being unpublished -> this is the reason for the error. 

![image](https://user-images.githubusercontent.com/20074364/183897376-577068e1-a739-463d-8b40-5439e21510da.png)

The beneath screenshot is the error when trying to access one of the items in the listview -> no constructive message is being returned. 

![image](https://user-images.githubusercontent.com/20074364/183897560-39919faa-12d2-480d-8f2b-6380be6c599e.png)

The next sceenshot shows the error from the logviewer:

![image](https://user-images.githubusercontent.com/20074364/183897799-9843247e-a5ec-4df4-a571-efeb7ba7b079.png)

It seems like this issue stems from this DLL: Umbraco.Cloud.Headless.Backoffice.dll: 2.12.0.0

The code within the DLL cant process when a parent node is not published when culture variance is enabled because the parent node when not published doesn't contain a URL -> and the DLL expects a URL hence the error message:

System.ArgumentException: Value cannot be null or whitespace.
Parameter name: text
   at Umbraco.Web.Routing.UrlInfo..ctor(String text, Boolean isUrl, String culture)

I have tested this one out on my own project: https://www.s1.umbraco.io/project/hc-muslim-test

## Specifics versions

![image](https://user-images.githubusercontent.com/20074364/183898942-a6e57917-3f4b-4ba9-8a17-a1503dda0623.png)

## Is it possible to Reproduce? 
Then describe the steps below

1. Add a language (french) 
2. Create a document type for the parent node and enable culture variance in the permissions section and allow as root
3. Create a documen type for the child node and enable culture variance in the permissions section and allow as child to the above
4. Go to the content section create a parent node.
5. Then create a child node in english save / publish -> try to access that child node -> everything is good
6. Then create a child node in french save / publish -> it will throw error.
7. Try access the child nodes in english now -> you wont be able to hence everything gets corrupted under the parent node.
8. You should receive the error (remember not to save and publish the parent node only child nodes)

## Solution
Workaround would be to save and publish the parent node in both languages

## Expected behavior
Not sure if this is intended but either way we should get a much better error message. And also it should not result in ALL child nodes being corrupted (both in english and french) 

Let me know if anything - PS -> Muslim Umbraco Swat.

**Comment by sitereactor** [comment]
We have a version 2.14.4 in development, which should fix this. @thejokerd3 please reach out if you want to verify the fix for this.

**Comment by sitereactor** [comment]
The update has been rolled out, so we consider this fixed unless @thejokerd3 reports back and is able to reprodue the issue.
