### ISSUE TITLE
Feature Request: Include media items properties on content transfer

### ISSUE THREAD

**Issue by Hanskrogh** [umbraco/Umbraco.Heartcore.Issues#64]
### Issue description

Hi.

When you're doing a content transfer between environments, the properties on the media items that is connected to items isn't updated on the new environment.

Example:
<img width="2503" alt="Screenshot 2022-08-24 at 12 49 08" src="https://user-images.githubusercontent.com/43749842/186400276-35c160b0-2f05-46dd-b4dd-07a8cdbbd67d.png">

We move the content where this image is used, the "alt" property on the image, isn't being updated on the new environment.

**Comment by sitereactor** [comment]
I'm checking on this internally as its something I would expect to 'just work' when transfering content/media between environments.

**Comment by Hanskrogh** [comment]
I can confirm that it dosn't work for atleast nested media items, so if we have an media picker within a media picker, it is only the parent media picker, that get's transferred.

**Comment by sitereactor** [comment]
I got this back from our Umbraco Deploy team

> The only scenario I can see that perhaps matches the request is this, but it's expected behaviour:
> - Populate a media picker property on a media item with a related media item.
> - Ensure the related media item is newly created in the downstream environment and that it has an alt tag set on an added text string property.
> - Transfer the first media item - the related one is also transferred and created in the upstream environment, with all it's properties.
> - Update the alt tag on the related item.
> - Update the first media item and transfer it - the updated alt tag on the related item is NOT updated.
> - But this is expected - Deploy checks that related content and media from pickers exist in the target environment and creates them if not.  But if they exist it doesn't update them unless they are individually selected for the transfer.

So when the change is indirect its not transfered if simply updated. It is transfered if its new and thus missing in the destingation. When its indirect its not obvious to the user that a change at the 3rd level is transfered, which is why its not transfered. In these scenarios you need to be explicit about what is transferred.

**Comment by sitereactor** [comment]
Closing this one, as we can't go beyond the scenario described above.
