### ISSUE TITLE
Bug: Culture and links

### ISSUE THREAD

**Issue by Hanskrogh** [umbraco/Umbraco.Heartcore.Issues#71]
### Issue description

If you link to a document node that is not published in the current culture, it will return url as "#" instead of the url for the fallback culture, which the page is published in.

This is quite a big issue, since you have to publish all pages in all cultures for the solution to work.

We have made a workaround currently but it is super hacky. So it would be nice if you could look into supporting this in the future!

**Comment by sitereactor** [comment]
I changed this to "Needs Investigation" as we need to double check the expected scenarios with the CMS team. At this point I'm not 100% sure if what you expect is how it's intended to work. But I will figure it and report back.

**Comment by RSoeborg** [comment]
@sitereactor Can you give us an email where we can continue this conversation privately, we would like to provide a more detailed description about how the issue affects us and how we use Umbraco internally.

**Comment by jmf-umbraco** [comment]
Since it seems like you have been in touch with HQ and perhaps received some guidance around how to achieve what you want, I'm going to close this issue for now. If anything is still outstanding, please feel free to re-open or raise a new issue!
