### ISSUE TITLE
Bug: Content Picker returns null when selecting content in a List View

### ISSUE THREAD

**Issue by HamDerAndrew** [umbraco/Umbraco.Heartcore.Issues#72]
### Issue description

When you select content, via the Content Picker, and that conten is inside a List View, it will return null in the REST response.
If you select content that is not in a List View it works fine and returns the data in the REST response.
I was able to reproduce this on two Heartcore projects.

## Steps to reproduce:
1. Make a document type with a Content Picker property and allow it as Root. Let's call it "Home"
2. Make a document type that acts as the container for the List View items. Allow it as Root. Enable List View. Let's call it "Content Container".
3. Make a document type with a Content Picker property and allow it as a child under the container document type above. Let's call it "Content Item".
4. Make a document type that will act as the content to pick. Allow it as Root. Let's call it "Test Content"

Now we will make a setup of the content like so:
-Home
-Test Content
-Content container
--Content Item

Follow these steps to make the setup:
1. Make the Test Content node and apply content.
2. Make the Content Container for the List View items.
3. Add a Content Item in the Content Container. On the Content Item here, pick the Test Content
4. Make a Home content node and use its Content Picker to pick the Content Item in the list in the Content Container.
5. Run a GET request on the Home node and check if the value for the Content Picker is null . It should be and there in lies the issue.
6. In the Home content node, pick the Test Content directly from the Content root level.
7. Run a GET request on the Home node again and check if the Content Picker value now returns the content that is picked. It should do that.

**Comment by sitereactor** [comment]
@HamDerAndrew can you post this bug report along with your test projects in the Heartcore Slack channel so we can investigate.
We have examples where this works as intended, so to make sure we have the scenario and output correct it would be good to have the projects available for testing.

**Comment by HamDerAndrew** [comment]
Alright, so what is happening here is the intended behaviour.
The properties that are `null` are on a picked item.
By default only referenced items that are directly on the content you query, is resolved.

It's possible to change this by using the `depth` query string param.
We have more on that in our documentation here:
https://docs.umbraco.com/umbraco-heartcore/api-documentation/content-delivery/content#depth

Kudos to Rasmus from the Heartcore team for letting me know this.

Closing the issue 😀
