### ISSUE TITLE
Content Management API: Create Media returns  "The specified file type has been disallowed by the administrator" error

### ISSUE THREAD

**Issue by wvankesteren-ax** [umbraco/Umbraco.Heartcore.Issues#73]
### Issue description

Using c# package Umbraco.Headless.Client.Net.Web 1.4.0 and IContentManagerService.Media.Create() I'm trying to upload a jpg or png file, but getting an error.

There are two issues here:

-  It's not really clear that the call fails. The only way is checking Media.GetValue("error");
-  Can't get the creation of media to work. The returned error is: 

`
        {
         "error": {
		        "code": "ValidationFailed",
		        "message": "Validation error.",
		        "details": {
			        "errors": {
				        "umbracoFile": [
					        "The specified file type has been disallowed by the administrator"
				        ]
			        }
		        }
	        }
        }
`
please note that in the backend with the specified file type (e.g. jpg, png, txt, pdf) it is possible to upload!

**Comment by martijnbeumers** [comment]
@nul800sebastiaan pls have a look at this item. Thanks. :)

**Comment by RyuLindow** [comment]
Have either of you reached out to our support about this issue, so that they can try to reproduce and investigate it?

**Comment by wjvankesteren** [comment]
[Media.zip](https://github.com/umbraco/Umbraco.Heartcore.Issues/files/9870311/Media.zip)

I've created a (test) class that can be used to reproduce the issue.
usage:

            MediaNode mediaNode = new(_contentManagerService, _logger);

            mediaNode.Test();

**Comment by RyuLindow** [comment]
Please, work with support on this issue and they'll escalate this internally if necessary.

If you can provide them with the query, so that they can reproduce this using e.g. Postman or another API dev tool.

Also, I don't recommend uploading any files you don't want to be public here. Our support, on the other hand, is a secure/closed channel :)

**Comment by wjvankesteren** [comment]
thanx! See also support ticket 74671

**Comment by sitereactor** [comment]
TODO for the Heartcore team - update documentation and sample for uploading media using the .net client library.

**Comment by devantler** [comment]
Hi everyone. I have had the pleasure of looking into this to improve the documentation. There is a [PR](https://github.com/umbraco/UmbracoDocs/pull/4663) here, so if anyone wants to give some feedback or thinks something is missing, feel free to comment here or on the linked PR.

**Comment by RyuLindow** [comment]
My preferred approach is to manually upload the media file via the backoffice and then fetch the data for it to see the JSON for it for reference.

**Comment by wjvankesteren** [comment]
that could be a tip in the documentation as well...

**Comment by RyuLindow** [comment]
Fair point. Actually, had some people mention it yesterday and plan to look into updating the docs with a note about it next week :)

**Comment by wjvankesteren** [comment]
Many thanx!

n.b. In the related support ticket the following link was mentioned (that's what I meant):

https://our.umbraco.com/Documentation/Umbraco-Heartcore/API-Documentation/Content-Management/media/#create-media:~:text=Content%2DDisposition%3A%20form%2Ddata%3B%20name%3D%22content%22%0AContent%2DType%3A%20application/json%0A%0A%7B-,%22mediaTypeAlias%22%3A%20%22Image%22%2C,-%22name%22%3A%20%22Han%20Solo%22%2C%0A%20%20%20%20%22parentId%22%3A%20%227bfa2332%2Dcf7f%2D4c97%2D941d%2D50f43f085b06%22%2C%0A%20%20%20%20%22umbracoFile

**Comment by sitereactor** [comment]
Just a quick update here, as two parts has been merged into the docs already and we'll add some more cases for media as per customer feedback. Keeping this issue open until those last cases have been documented as well.

**Comment by wvankesteren-ax** [comment]
many thanx!

**Comment by sitereactor** [comment]
Closing this issue as we have expected the docs with a few different things:

- Article about creating media and media references using the management api: https://docs.umbraco.com/umbraco-heartcore/tutorials/creating-content-with-media
- API documentation for creating media: https://docs.umbraco.com/umbraco-heartcore/api-documentation/content-management/media#create-media
- And finally the Console sample in the .net client library has been updated with more use cases for media: https://github.com/umbraco/Umbraco.Headless.Client.Net/tree/master/samples/Umbraco.Headless.Client.Samples.Console
