### ISSUE TITLE
Webhook publish content event fires up twice

### ISSUE THREAD

**Issue by PMendesWebDev** [umbraco/Umbraco.Heartcore.Issues#74]
### Issue description

I'm triggering a webhook when a node is published, unpublished and deleted (3 different webhooks).

Everytime I unpublish or delete a node, the respective webhook is fired once per action - which is an expected behavior.
But when a node is published, the respective webhook is fired once or twice.

I have 2 languages in the CMS and when the webhooke is fired twice, it seems that it is firing for each language use (the first requests contains one languange, the second contains the other language). But this is not happening to every node, which is odd...

I'm available to give you more information on this if needed be.

**Comment by RyuLindow** [comment]
The easiest way to provide more details is to reach out to our support. Have you opened a ticket with them yet?

**Comment by PMendesWebDev** [comment]
Thanks for the fast reply @RyuLindow

Sorry for the dumb question... ...but how can I open a ticket? 😅

**Comment by RyuLindow** [comment]
There's a floating chat bubble in the bottom right of the [Cloud portal](https://www.s1.umbraco.io/projects) or send a mail via - https://umbraco.com/contact-us/

**Comment by PMendesWebDev** [comment]
Ok, I thought that was only intended for Umbraco **Cloud** issues xD

Thanks @RyuLindow!

**Comment by RyuLindow** [comment]
No, that's for anything Umbraco related :)

For now, please work with the support team on this and if the conclusion is that it's a Heartcore bug then feel free to reopen this issue.
