### ISSUE TITLE
Feature Request - Add a copy button to json input and output fields on webhook logs

### ISSUE THREAD

**Issue by davemanton** [umbraco/Umbraco.Heartcore.Issues#79]
### Issue description

When working with webhook logs we have frequently wanted to replay the data in our own environment or copy the data into something like notepad so we can investigate where we might be seeing a problem

Currently we have to select the data using the mouse which for large payloads is particularly painful

Please could you add a copy button which places json payloads from webhook logs onto the clipboard

**Comment by jmf-umbraco** [comment]
Hi @davemanton,

I know it's been a while since this was raised, but just wanted to thank you for your suggestion and let you know that it's under consideration for a future release. We don't have a timeframe at this stage, but will let you know when we know more.

**Comment by jmf-umbraco** [comment]
Hi @davemanton,

We've recently adopted the same webhook UI as the core CMS, and it happily already supports this feature. It should now be available in all sites!
