### ISSUE TITLE
Feature Request: partial / fuzzy search for content

### ISSUE THREAD

**Issue by felixcicatt** [umbraco/Umbraco.Heartcore.Issues#85]
### Issue description

Currently the search endpoint for Heartcore only supports searching for exact words. Searching for part of a word seems like a minimum requirement for such a feature, but having fuzzy search capabilities would be great.

**Comment by sitereactor** [comment]
Thank you for submitting this feature request!
The Search capabilities available in Heartcore is something we hope to revise at some point this year. I don't have a specific time frame yet, but I'm hoping we can get to a place where a Search endpoint will support features like Fuzzy search.

**Comment by fransen** [comment]
We have started to implement Heartcore and this is one that is absolutely on our list of requirements. Search does work at this point, but it feels rather limited.

Is there an update on the timepath of this feature?

**Comment by royberris** [comment]
Hi, any update on this? Searching right now is very limited. We are looking at external indexes to solve our more complex search queries. Would be nice to do this with the heartcore search API

**Comment by jmf-umbraco** [comment]
Hi all,

Where search is concerned, we have some improvements that we wish to make. More specifically, we are currently using a limited SQL-based search provider and we intend to investigate transitioning to Azure AI search or equivalent alternative.

Unfortunately this is quite a major piece of work and will thus it will be some time before we are ready to commence it - we likely will not be starting this work until end of 2024 at the earliest.

We are going to close this issue for now and we will share more information when we are ready to start diving in to search improvements as a whole.

**Comment by jamesbrowneuk** [comment]
Appreciate this ticket was closed back in 2023, but there is a reference to work on this feature potentially starting at the end of 2024.  Can you confirm the status of this?
