### ISSUE TITLE
Unable to retrieve map results in GraphQL 

### ISSUE THREAD

**Issue by adam1403csi** [umbraco/Umbraco.Heartcore.Issues#86]
### Issue description

Using the inbuilt Our.Umbraco.GMaps property editor, we are unable to retrieve the map location in GraphQl queries, with the following response returned from the Graph query: "message": "Error trying to resolve field 'map'.",

This has been raised to support in ticket ID 76299, who have asked me to raise this as a bug request.

**Comment by sitereactor** [comment]
Hi @adam1403csi thanks for flagging this. We have a fix for this, which is ready to be released as soon as its tested and verified.

Will report back once its released.

**Comment by sitereactor** [comment]
We have rolled out a fix for the GraphQL part of the Google Maps editor in Umbraco Heartcore, so closing this issue and marking as fixed.
