### ISSUE TITLE
Feature Request: Allow the use of 'where' on custom properties

### ISSUE THREAD

**Issue by andyfrost97** [umbraco/Umbraco.Heartcore.Issues#88]
### Issue description

On a GraphQL query wtihin Heartcore, would it be possible to allow for support of "filtering" by custom properties on a document type.
```children(first:$limit orderBy:$order after:$cursor where: { AND: [ {name_contains: $search}, {} ] } ) {}```
On the above query on the `AND:`, We would like to add additional items here that relate to the properties we have added to a document type (and not just name, create date, etc.).

**Comment by sitereactor** [comment]
Thanks for submitting this feature request. We will consider it as an improvement for GraphQL.
Right now I don't have a timeframe for it, as we have planned work that needs to be concluded first.

**Comment by jmf-umbraco** [comment]
Hi @andyfrost97,

Sorry for lack of response until now. Unfortunately with the nature of our GraphQL implementation and its strong static typing, this is not something that we are able to implement at this time.
