### ISSUE TITLE
GraphQL: Different fragments that selects the same "URL" field can show null in its response.

### ISSUE THREAD

**Issue by Frost117** [umbraco/Umbraco.Heartcore.Issues#89]
Let's say you have a lot of fragments. In some cases you'll end with fragments that targets the same field. Kinda like this:

``` 
fragment MyFirstFragment on MyFirstFragment {
  name
  url
  selectedImage {
   ... on Image {
      name
      url
      umbracoWidth
    }
  }
}

fragment MySecondFragment on MySecondFragment {
  name
  url
  selectedImage {
    ... on Image {
      name
      url
      umbracoWidth
    }
  }
}  
```

Then the url of the selectedImage  in the MyFirstFragment would turn out with something like this:

![image](https://user-images.githubusercontent.com/32164310/216922017-29f5098a-2a64-4c01-90a4-978f4f622e20.png)

You can workaround this by using the umbracoFile instead of the Image, to get the url generate like so:

```
fragment MyFirstFragment on MyFirstFragment {
  name
  url
  selectedImage {
   ... on Image {
      name
       umbracoFile{
        url
      }
    }
  }
}
```

**Comment by sitereactor** [comment]
Currently scheduled for release between 28-31. March

**Comment by rasmusjp** [comment]
Closing this as it was deployed some time ago, if it's still an issue feel free to reopen
