### ISSUE TITLE
Content Delivery Platform does not index elements (nested content)

### ISSUE THREAD

**Issue by felixcicatt** [umbraco/Umbraco.Heartcore.Issues#92]
### Issue description

One of your colleagues from Support explained to me that the *Content Delivery Platform*, which is used by newer installments of Heartcore, does not index elements (nested content) as part of pages. This means we can't use the [search endpoint](https://docs.umbraco.com/umbraco-heartcore/api-documentation/content-delivery/content#search) to search within nested content. This renders the search endpoint useless for some of our projects. The *CMS Instance*, which is used by older installments, does support this use case.

They said you were looking into this internally. We would appreciate it if you could update us on the status here.

**Comment by sitereactor** [comment]
We talked about this in the team, and its something that should be part of the search so we will incorporate it into what is indexed and thus searchable via the Search endpoint. We're currently looking at getting it done during next Sprint starting Monday April 24nd.

The team will report back once its ready to be released.

**Comment by rasmusjp** [comment]
We've deployed an update yesterday enabling the search endpoint to also search in elements (Nested Content and Block List)
